### ISSUE TITLE
NVME_IOCTL_IO_CMD & NVME_IOCTL_IO64_CMD not future proof

### ISSUE THREAD

**Issue by clay-mayers** [joshkan/nvme-uring-pt#3]
The NVME passthru types the return result by having two IOCTLs and command structures - one for 32-bit results and one for 64-bit results.  However, `NVME_IOCTL_IO_CMD` & `NVME_IOCTL_IO64_CMD` are not the only possibilities.  Instead of a single u64, the result could be two u32s (cqe.dw0/result and cqe.dw1). Maybe you could use `NVME_IOCTL_IO64_CMD` for this case but that creates endian aware client code.   Because all the values passed in and out of `nvme_passthru_cmd64` are cpu endian. It would require converting the u64 result to LE and shifting/masking the two u32s, making the client be endian aware.  This is in contradiction to having all the values in cpu endianness.  I am sort of suggesting adding a 3rd IOCTL/struct pair but there already is a lot of code duplication as it is and creating a user API should not be taken lightly.

I understand the urge for uring to use the same IOCTLs and structures as `ioctl()` but I don't think it should inherit the dual passthru legacy from `ioctl()`.  If you stick with the goal to have clients not be endian aware it also can't just use `NVME_IOCTL_IO64_CMD`.  I think uring needs a different IOCTL/cmd pair with two u32s as the result ***only***.  It would expose the cqe dw0 & dw1 entries as cpu endian values.  The client can use dw0 and or dw1 as required by the command as well as ((u64)dw1<<32)+dw0 with no endian code.  This is no different than the input nvme_passthru members cdw10 and above, although a little more work for u64 results.

That said, I think the code could be restructured to share far more code and support a 3rd result type for `ioctl()` but I still would suggest to not support what I see are backward compat IOCTLs for u32 and u64 bit results in uring.

As part of writing this up I noticed that `nvme_submit_user_cmd()` converts the result to cpu endianness ***always as a u64*** (which I believe is wrong for `nvme_passthru_cmd` on a BE cpu).  Code on a BE cpu using NVME_IOCTL_IOCMD will be looking at cqe.dw1 instead of cqe.result/dw0.  A further indication that the split ioctls (required for backward compat) creates so much duplication a bug slipped through trying to share the `nvme_submit_user_cmd()` code between the two.

I'm going to try and find when IO64 was added to see what the reasoning was for how it was implemented.  What are your thoughts and doubts?

**Comment by clay-mayers** [comment]
The commit that added IO64 was 65e68edce0db4.  To my surprise, it was added for fabrics and not zns initially.

The infradead email archive for nvme seems to be missing all of 2019 and part of 2018 but I found the patch on x-lore: https://x-lore.kernel.org/linux-nvme/786558932.78398145.1569330892814.JavaMail.zimbra@kalray.eu/

The discussion it references as [2] is 404 and not that informative as to reasoning for the patch - again on x-lore: https://x-lore.kernel.org/linux-nvme/CAPrnrPD2PtPO38cAzMfKdhS18GFj1vk032p0h0rQf0CFP+R=cw@mail.gmail.com/

**Comment by joshkan** [comment]
If I got you right, you are highlighting the absence of support when a passthru command is returning two 32 bit results (rather than single 32/64 bit result). Do you see that kind of commands are more common? 
And I think that has a different scope than this patchset. We need to discuss the need of such ioctl in mailing list and get that introduced in nvme first. The exact nvme-ioctl is opaque as far as uring is concerned.....it is sending uring-cmd down to driver and driver decides how to process the contained ioctl-code. Do you have different views?

**Comment by clay-mayers** [comment]
We have commands like that in our command set - I agree that it's beyond this patch set at this point.  But once there's agreement on how to implement uring-ioctl, I think it's germane.  I don't remember who on the list it was, but I recall a notion of being able to drop some of the ioctl baggage with a uring-ioctl.  I see this as nvme-ioctl baggage that there are two passthru commands.

I absolutely agree nvme-ioctl is opaque but endianess requires some interpretation.  You've made me reconsider my position.  The patch set is good to only support 64-bit passthru (never adding 32-bit) - I would prefer two 32-bit results because it's a more a direct mapping of nvme-result to passthru-result but I now see that's mostly arbitrary.

**Comment by joshkan** [comment]
Earlier version included support for 32 bit passthru too, but we dropped it because (1) that was the recommendation from community (2) plumbing got cleaner/reduced.
Even in current scheme of things, I want to reduce the need of reporting two kind of results....one result goes into cqe (cqe->res), another goes into user-space field. Keeping only cqe result would be more efficient from perf PoV. But it would compel applications to treat async passthru command more differently than sync passthru.  

On a different note, may I ask how are you (Kioxia) planning to leverage uring ioctl? Do you see this interface is important for SEF.

**Comment by clay-mayers** [comment]
I'd say uring ioctl is required for SEF.  The SEF command set is such that we can't use the bio layer.  It also has command pairs making it impossible to use a sync interface on a single thread.  It's required to have an async interface and uring is the most direct path for that.  Our proto-type uses uring ioctl for all async commands on both the char (controller) and block device (namespace).

**Comment by clay-mayers** [comment]
I was unaware this has already been addressed by the community - it seems 64-bit is the answer.  I'm going to close this issue.

**Comment by joshkan** [comment]
Thanks for the update.
